config/routes.rb
Rails.application.routes.draw do
  resources :students
  root 'students#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    def show
        @student = Student.find_by(student_number: params[:id])
        respond_to do |format|
            format.html
            format.pdf do
                render pdf: @student.student_number+"_"+@student.name,
                template: "/students/show.pdf.erb",
                layout: "pdf.erb"
            end
        end
    end

    def index
        @students = Student.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodeTest Students</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/pdf.erb
<html>
  <head>
    <%= wicked_pdf_stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= wicked_pdf_javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= wicked_pdf_javascript_include_tag 'qrcode.min', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_details.html.erb
<div>
	<div class="page-header">
		<h1><%= @student.name %></h1>
	</div>
	<div class="row">
		<div class="col-xs-4">
			<b>Student No.</b>
		</div>
		<div class="col-xs-8">
			<%= @student.student_number %>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-4">
			<b>Faculty</b>
		</div>
		<div class="col-xs-8">
			<%= @student.faculty %>
		</div>
	</div>
</div>

app/views/students/index.html.erb
<div class="container">
	<h1>Students</h1>     
  <div class="list-group">
    <% @students.each do |student| %>
      <a href=<%=student_path(student.student_number)%> class="list-group-item list-group-item-action"><%=student.name%></a>
    <% end %>
	</div>
</div>

app/views/students/show.html.erb
<div class="container">
	<%= render 'details' %> 
	<br/>
	<div>
		<a href=<%=@student.student_number.to_s + '.pdf'%> class="btn btn-primary" role="button">
			<span class="glyphicon glyphicon-download-alt"></span>
			<span>&nbsp; Download PDF</span>
		</a>
	</div>
</div>

app/views/students/show.pdf.erb
<div class="container">
  <%= render '/students/details.html' %> 
  <br/>
  <div id="qrcode"></div>
</div>  

<script type="text/javascript">
  new QRCode(document.getElementById("qrcode"), {
    width: 128,
    height: 128, 
    text : "<%= @student.student_number %>"
  });
</script>